apiVersion: v1
kind: Service
metadata:
  name: cp-zookeeper-headless
  labels:
    app: cp-zookeeper

spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: cp-zookeeper