apiVersion: v1
kind: Service
metadata:
  name: cp-schema-registry
  labels:
    app: cp-schema-registry

spec:
  ports:
    - name: schema-registry
      port: 8081
  selector:
    app: cp-schema-registry