apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-ksql-server
  labels:
    app: cp-ksql-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-ksql-server
  template:
    metadata:
      labels:
        app: cp-ksql-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
    spec:
      containers:
        - name: prometheus-jmx-exporter
          image: "solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143"
          imagePullPolicy: "IfNotPresent"
          command:
          - java
          - -XX:+UnlockExperimentalVMOptions
          - -XX:+UseCGroupMemoryLimitForHeap
          - -XX:MaxRAMFraction=1
          - -XshowSettings:vm
          - -jar
          - jmx_prometheus_httpserver.jar
          - "5556"
          - /etc/jmx-ksql-server/jmx-ksql-server-prometheus.yml
          ports:
          - containerPort: 5556
          resources: {}
            
          volumeMounts:
          - name: jmx-config
            mountPath: /etc/jmx-ksql-server
        - name: cp-ksql-server
          image: "confluentinc/cp-ksqldb-server:5.5.0"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: server
              containerPort: 8088
              protocol: TCP
            - containerPort: 5555
              name: jmx
          resources: {}
            
          volumeMounts:
          env:
          - name: KSQL_BOOTSTRAP_SERVERS
            value: PLAINTEXT://cp-kafka-headless:9092
          - name: KSQL_KSQL_SERVICE_ID
            value: mokul
          - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
            value: http://cp-schema-registry:8081
          - name: KSQL_HEAP_OPTS
            value: "-Xms512M -Xmx512M"
          - name: KSQL_LISTENERS
            value: http://0.0.0.0:8088
          - name: JMX_PORT
            value: "5555"
          - name: KSQL_KSQL_CONNECT_URL
            value: http://cp-kafka-connect:8083
      volumes:
      - name: jmx-config
        configMap:
          name: cp-ksql-server-jmx-configmap
